enum EStudentActions {
  GET_STUDENTS = "GET_STUDENTS",
  GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST",
  GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS",
  GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE",

  CREATE_STUDENT = "CREATE_STUDENT",
  CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST",
  CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS",
  CREATE_STUDENT_FAILURE = "CREATE_STUDENT_FAILURE",

  UPDATE_STUDENT = "UPDATE_STUDENT",
  UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST",
  UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS",
  UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE",

  DELETE_STUDENT = "DELETE_STUDENT",
  DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST",
  DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE",

  ENROLL_COURSE = "ENROLL_COURSE",
  ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST",
  ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS",
  ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE",

  CANCEL_COURSE = "CANCEL_COURSE",
  CANCEL_COURSE_REQUEST = "CANCEL_COURSE_REQUEST",
  CANCEL_COURSE_SUCCESS = "CANCEL_COURSE_SUCCESS",
  CANCEL_COURSE_FAILURE = "CANCEL_COURSE_FAILURE",
}

export { EStudentActions };
